### ISSUE TITLE
k8s version adaptive with pvc annotation

### ISSUE THREAD

**Issue by whg517** [zncdatadev/secret-operator#120]
env:

- kind k8s 1.27.11

`volume.beta.kubernetes.io/storage-provisioner` deprecated since v1.23.

https://kubernetes.io/docs/reference/labels-annotations-taints/#volume-beta-kubernetes-io-storage-provisioner-deprecated

deploy a resource use tls secretclass to provide a pvc

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: openjdk:11
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: foo
          mountPath: /opt/secret/foo
      volumes:
      - name: foo
        ephemeral:
          volumeClaimTemplate:
            metadata:
              annotations:
                secrets.zncdata.dev/class: tls
                secrets.zncdata.dev/format: tls-p12
                secrets.zncdata.dev/scope: pod,node
                secrets.zncdata.dev/tlsPKCS12Password: xyz
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: secrets.zncdata.dev
              resources:
                requests:
                  storage: 1Mi

```

this is a pvc created by deployment controller base ephemeral.volumeClaimTemplate

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    secrets.zncdata.dev/class: tls
    secrets.zncdata.dev/format: tls-p12
    secrets.zncdata.dev/scope: pod,node
    secrets.zncdata.dev/tlsPKCS12Password: xyz
    volume.beta.kubernetes.io/storage-provisioner: secrets.zncdata.dev
    volume.kubernetes.io/storage-provisioner: secrets.zncdata.dev
```

the log in secret-csi

```golang
2024-09-11T07:21:31Z    INFO    volume  Unknown key, skip it    {"key": "volume.beta.kubernetes.io/storage-provisioner", "value": "secrets.zncdata.dev"}
2024-09-11T07:21:31Z    INFO    volume  Unknown key, skip it    {"key": "volume.kubernetes.io/storage-provisioner", "value": "secrets.zncdata.dev"}
```
