### ISSUE TITLE
Empty DN value in generated tls

### ISSUE THREAD

**Issue by whg517** [zncdatadev/secret-operator#136]
```
java.io.UncheckedIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:
    certificate: sha256/VbbefBUad02SkWoJsAGrnJ0VOlBIkNnNOoFaFmXEppk=
    DN: 
    subjectAltNames: [172.18.0.2, trino-operator-1.26.14-control-plane, trino-coordinat
```
